[build]
  command = "npm run build"

[functions]
  directory = ".netlify/v1/functions"
  node_bundler = "none"
  included_files = [".netlify/v1/functions/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "22.13.0"